/**
 * Generates TypeScript types and Pydantic models from the JSON Schemas.
 *
 * The schemas in src/ are the single definition of RoomModel, ObjectsFile,
 * LayoutPlan and ValidationReport (implementation-plan.md 2.4). Nothing in
 * generated/ is edited by hand; CI runs this with --check and fails if the
 * committed output differs, which is what stops TypeScript and Python drifting
 * apart silently.
 */
import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  writeFileSync,
  readdirSync,
  existsSync,
  rmSync,
  unlinkSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { spawnSync } from "node:child_process";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const SRC = join(here, "..", "src");
const TS_OUT = join(here, "..", "generated");
const PY_OUT = join(here, "..", "..", "..", "workers", "schemas_py", "roomfittr_schemas");

const check = process.argv.includes("--check");

/** Documents we generate a top-level type for. common is shared definitions only. */
const DOCS = [
  ["room-model.schema.json", "RoomModel", "room_model"],
  ["objects-file.schema.json", "ObjectsFile", "objects_file"],
  ["layout-plan.schema.json", "LayoutPlan", "layout_plan"],
  ["validation-report.schema.json", "ValidationReport", "validation_report"],
];

const BANNER = "/* GENERATED by packages/schemas/scripts/generate.mjs. Do not edit. */\n";
const PY_BANNER = '"""GENERATED by packages/schemas/scripts/generate.mjs. Do not edit."""\n';

const readSchema = (f) => JSON.parse(readFileSync(join(SRC, f), "utf8"));

/* -------------------------------------------------------------------------- */
/* TypeScript                                                                  */
/* -------------------------------------------------------------------------- */

async function generateTs() {
  const out = {};
  for (const [file, title] of DOCS) {
    const ts = await compile(readSchema(file), title, {
      cwd: SRC,
      bannerComment: "",
      additionalProperties: false,
      style: { semi: true, singleQuote: false },
    });
    out[`${file.replace(".schema.json", "")}.ts`] = BANNER + ts;
  }

  const index = DOCS.map(
    ([file, title]) => `export type { ${title} } from "./${file.replace(".schema.json", "")}.js";`,
  ).join("\n");
  out["index.ts"] = BANNER + index + "\n";
  return out;
}

/* -------------------------------------------------------------------------- */
/* Pydantic                                                                    */
/*                                                                             */
/* datamodel-code-generator does the work. Hand-rolling a JSON Schema to        */
/* Pydantic compiler was the first attempt and it flattened every nested object */
/* to dict[str, Any], which throws away exactly the typing the schemas exist to */
/* provide. Shelling out to the standard tool keeps the nested models real.     */
/* -------------------------------------------------------------------------- */

function generatePy() {
  // The schemas $ref across files, so the tool needs a package directory
  // rather than one module. It is generated into a temp dir and compared
  // wholesale, so --check can tell the truth without touching the tree.
  const tmp = mkdtempSync(join(tmpdir(), "roomfittr-schemas-"));

  const args = [
    "run", "datamodel-codegen",
    "--input", SRC,
    "--input-file-type", "jsonschema",
    "--output", tmp,
    "--output-model-type", "pydantic_v2.BaseModel",
    "--target-python-version", "3.11",
    "--use-annotated",
    "--use-standard-collections",
    "--use-union-operator",
    "--enum-field-as-literal", "all",
    "--use-title-as-name",
    "--collapse-root-models",
    "--disable-timestamp",
    "--formatters", "ruff-format",
  ];

  // Windows needs shell:true to resolve uv.exe through PATHEXT, and a shell
  // splits unquoted arguments on spaces. Temp paths under C:/Users/First Last
  // have one, so every argument is quoted.
  const useShell = process.platform === "win32";
  const res = spawnSync("uv", useShell ? args.map((a) => `"${a}"`) : args, {
    encoding: "utf8",
    shell: useShell,
  });
  if (res.status !== 0) {
    console.error(res.stdout || "", res.stderr || "", res.error ?? "");
    throw new Error("datamodel-codegen failed");
  }

  const out = {};
  for (const name of readdirSync(tmp)) {
    if (!name.endsWith(".py")) continue;
    // Drop the tool's own comment header so the file opens with our banner.
    // --disable-timestamp already makes its output byte-stable.
    const body = readFileSync(join(tmp, name), "utf8")
      .replace(/^(?:#[^\n]*\n)+/, "")
      .replace(/^\n+/, "");
    out[name] = PY_BANNER + body;
  }

  // Own the package entry point rather than shipping the tool's, so the four
  // document models are the public surface and nothing else leaks out.
  // The tool names a module after the whole filename, so room-model.schema.json
  // becomes room_model_schema.py.
  const modules = DOCS.map(([file, title]) => [file.replace(".json", "").replace(/[-.]/g, "_"), title]);
  out["__init__.py"] =
    PY_BANNER +
    "\n" +
    modules.map(([mod, title]) => `from .${mod} import ${title}`).join("\n") +
    "\n\n__all__ = [\n" +
    modules.map(([, title]) => `    "${title}",`).join("\n") +
    "\n]\n";

  rmSync(tmp, { recursive: true, force: true });
  return out;
}

/* -------------------------------------------------------------------------- */

function emit(dir, files, exts) {
  mkdirSync(dir, { recursive: true });
  const stale = [];

  for (const [name, content] of Object.entries(files)) {
    const path = join(dir, name);
    const existing = existsSync(path) ? readFileSync(path, "utf8") : null;
    if (existing !== content) {
      stale.push(path);
      if (!check) writeFileSync(path, content);
    }
  }

  // A schema that was deleted must not leave its module behind, still
  // importable and quietly wrong.
  for (const name of readdirSync(dir)) {
    if (!exts.some((e) => name.endsWith(e))) continue;
    if (files[name] !== undefined) continue;
    stale.push(join(dir, name));
    if (!check) unlinkSync(join(dir, name));
  }

  return stale;
}

const schemas = Object.fromEntries(
  readdirSync(SRC)
    .filter((f) => f.endsWith(".schema.json"))
    .map((f) => [f, readSchema(f)]),
);

const stale = [
  ...emit(TS_OUT, await generateTs(), [".ts"]),
  ...emit(PY_OUT, generatePy(), [".py"]),
];

if (check && stale.length) {
  console.error(
    "Generated files are stale. Run `pnpm schemas:gen` and commit the result:\n" +
      stale.map((p) => `  ${p}`).join("\n"),
  );
  process.exit(1);
}
console.log(check ? "schemas: generated files are up to date" : `schemas: wrote ${stale.length} file(s)`);
