"""GENERATED by packages/schemas/scripts/generate.mjs. Do not edit."""

from __future__ import annotations
from typing import Annotated, Any
from pydantic import BaseModel, ConfigDict, Field, RootModel


class Common(RootModel[Any]):
    root: Annotated[
        Any,
        Field(
            description="Shared primitives. Defined once so the four documents cannot drift apart on units, id shapes or enum spellings.",
            title="Common",
        ),
    ]


class Point2Mm(RootModel[list[int]]):
    root: Annotated[
        list[int],
        Field(
            description="[x, z] on the floor plane, integer millimetres.",
            max_length=2,
            min_length=2,
        ),
    ]


class Size3MmItem(RootModel[int]):
    root: Annotated[int, Field(gt=0)]


class MoneyCents(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    amount_cents: Annotated[int, Field(ge=0)]
    currency: Annotated[str, Field(pattern="^[A-Z]{3}$")]


class SurfaceAppearance(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    color: Annotated[str | None, Field(pattern="^#[0-9a-fA-F]{6}$")] = None
    material: Annotated[str | None, Field(min_length=1)] = None
    texture_ref: Annotated[str | None, Field(min_length=1)] = None


class Footprint(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    center: Annotated[
        list[int],
        Field(
            description="[x, z] on the floor plane, integer millimetres.",
            max_length=2,
            min_length=2,
        ),
    ]
    size: Annotated[
        list[Size3MmItem],
        Field(
            description="[width, depth, height], integer millimetres, all positive.",
            max_length=3,
            min_length=3,
        ),
    ]
    rotation_deg: Annotated[
        float,
        Field(
            description="Degrees about +Y. An item's local front is -Z before rotation (2.4).",
            ge=0.0,
            lt=360.0,
        ),
    ]
    elevation_mm: Annotated[
        int,
        Field(
            description="Height of the item's underside above the floor. 0 for floor-standing items.",
            ge=0,
        ),
    ]
