"""GENERATED by packages/schemas/scripts/generate.mjs. Do not edit."""
from __future__ import annotations
from typing import Annotated, Literal
from pydantic import BaseModel, ConfigDict, Field


class Anchor(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Literal["wall", "opening", "slot", "region"]
    ref: Annotated[str, Field(min_length=1)]


class Intent(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    anchor: Annotated[
        Anchor | None,
        Field(
            description="What this slot is positioned relative to: a wall, an opening, or another slot."
        ),
    ] = None
    relation: Annotated[
        Literal["against_wall", "in_front_of", "under", "around", "beside", "float"]
        | None,
        Field(
            description="Closed list: these map one-to-one onto the solver's candidate-pose generators (5.4 L5.2). A relation the solver cannot generate poses for is worse than no relation at all."
        ),
    ] = None
    facing: Annotated[
        str | None,
        Field(description="What the item's front should point at.", min_length=1),
    ] = None
    notes: Annotated[
        str | None,
        Field(
            description="Free text for the solver's scoring hints and for explaining the plan. Never parsed as geometry.",
            max_length=500,
        ),
    ] = None


class Slot(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    slot_id: Annotated[str, Field(pattern="^S[0-9]+$")]
    category: Annotated[
        str,
        Field(
            description="Must exist in the category vocabulary; checked deterministically after the call, never trusted.",
            min_length=1,
        ),
    ]
    priority: Annotated[
        Literal["must", "should", "nice"],
        Field(
            description="Drop order when the room or the budget runs out: nice first, must last."
        ),
    ]
    budget_share: Annotated[
        float,
        Field(
            description="Fraction of budget. Renormalised to 100% with a 5% reserve after the call, so the model's arithmetic is never load-bearing.",
            ge=0.0,
            le=1.0,
        ),
    ]
    intent: Annotated[
        Intent | None,
        Field(
            description="What the slot wants, in terms the solver's candidate generators understand. Every id referenced is checked against the RoomModel before use."
        ),
    ] = None


class LayoutPlan(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Annotated[
        int,
        Field(
            description="Version of the schema set the document was written against.",
            ge=0,
        ),
    ]
    room_type: Annotated[
        str,
        Field(
            description="User-selected or inferred. Drives the default budget ratios and the category vocabulary.",
            min_length=1,
        ),
    ]
    style: Annotated[str | None, Field(min_length=1)] = None
    slots: Annotated[
        list[Slot],
        Field(
            description="One furniture opportunity each. Capped at 10 in V1 (5.4 post-checks).",
            max_length=10,
            min_length=1,
        ),
    ]
    rationale: Annotated[
        str | None,
        Field(
            description="Short, shown to the user. Why this set of furniture for this room.",
            max_length=1000,
        ),
    ] = None
