"""GENERATED by packages/schemas/scripts/generate.mjs. Do not edit."""

from __future__ import annotations
from typing import Annotated, Literal
from pydantic import BaseModel, ConfigDict, Field
from . import common_schema


class Obb(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    center: Annotated[
        list[int],
        Field(
            description="[x, y, z] in mm. Unlike floor geometry this carries height, so it is a 3-vector.",
            max_length=3,
            min_length=3,
        ),
    ]
    size: Annotated[
        list[common_schema.Size3MmItem],
        Field(
            description="[width, depth, height], integer millimetres, all positive.",
            max_length=3,
            min_length=3,
        ),
    ]
    yaw_deg: Annotated[
        float,
        Field(
            description="Degrees about +Y. An item's local front is -Z before rotation (2.4).",
            ge=0.0,
            lt=360.0,
        ),
    ]


class Object(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[str, Field(pattern="^B[0-9]+$")]
    label: Annotated[
        str,
        Field(
            description="The SAM 3 text prompt that matched, verbatim (3.5 S4).",
            min_length=1,
        ),
    ]
    label_group: Annotated[
        Literal["removable", "structure", "fixed"],
        Field(
            description="Which prompt group the label came from. This, not the label, decides `removable`."
        ),
    ]
    score: Annotated[float, Field(ge=0.0, le=1.0)]
    obb: Annotated[
        Obb,
        Field(
            description="Gravity-aligned oriented bounding box, trimmed to the 2nd-98th percentile of the instance's points to reject bleed."
        ),
    ]
    removable: Annotated[
        bool,
        Field(
            description="True for the removable prompt group. A `fixed` object that the user does not delete becomes a fixed_obstacle in the RoomModel."
        ),
    ]
    track_id: Annotated[
        int | None,
        Field(
            description="SAM 3 video track this instance came from, kept for debugging a bad merge.",
            ge=0,
        ),
    ] = None
    thumb_ref: Annotated[
        str | None,
        Field(
            description="R2 key of the crop shown in the keep-or-remove UI.",
            min_length=1,
        ),
    ] = None
    point_count: Annotated[int | None, Field(ge=0)] = None


class ObjectsFile(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Annotated[
        int,
        Field(
            description="Version of the schema set the document was written against.",
            ge=0,
        ),
    ]
    pipeline_version: Annotated[
        str,
        Field(
            pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-[0-9A-Za-z.-]+)?$"
        ),
    ]
    units: Literal["mm"]
    objects: list[Object]
