"""GENERATED by packages/schemas/scripts/generate.mjs. Do not edit."""
from __future__ import annotations
from typing import Annotated, Literal
from pydantic import BaseModel, ConfigDict, Field
from . import common_schema


class Wall(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[str, Field(pattern="^W[0-9]+$")]
    start: Annotated[
        list[int],
        Field(
            description="[x, z] on the floor plane, integer millimetres.",
            max_length=2,
            min_length=2,
        ),
    ]
    end: Annotated[
        list[int],
        Field(
            description="[x, z] on the floor plane, integer millimetres.",
            max_length=2,
            min_length=2,
        ),
    ]
    thickness_mm: Annotated[int, Field(ge=0, le=1000)]
    kind: Annotated[
        Literal["solid", "open"],
        Field(
            description="An `open` segment is a boundary with no wall behind it (open-plan edge, wide doorway). The solver treats it as a boundary but never places against it (3.6)."
        ),
    ]
    length_mm: Annotated[int, Field(ge=0)]


class Opening(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[str, Field(pattern="^O[0-9]+$")]
    wall_id: Annotated[str, Field(pattern="^W[0-9]+$")]
    type: Literal["door", "window", "passage"]
    offset_mm: Annotated[
        int, Field(description="Along the wall from its start vertex.", ge=0)
    ]
    width_mm: Annotated[int, Field(ge=1)]
    sill_mm: Annotated[
        int,
        Field(
            description="Height of the bottom edge above the floor. Doors are ~0.", ge=0
        ),
    ]
    height_mm: Annotated[int, Field(ge=1)]
    swing: Annotated[
        Literal["left", "right", "unknown"],
        Field(
            description="V1 usually cannot infer this. When unknown the validator keeps out both sides (5.5 H4)."
        ),
    ]
    confidence: Annotated[float, Field(ge=0.0, le=1.0)]


class FixedObstacle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: Annotated[str, Field(pattern="^F[0-9]+$")]
    label: Annotated[str, Field(min_length=1)]
    center: Annotated[
        list[int],
        Field(
            description="[x, z] on the floor plane, integer millimetres.",
            max_length=2,
            min_length=2,
        ),
    ]
    size: Annotated[
        list[common_schema.Size3MmItem],
        Field(
            description="[width, depth, height] in mm, in the obstacle's own frame before yaw.",
            max_length=3,
            min_length=3,
        ),
    ]
    yaw_deg: Annotated[
        float,
        Field(
            description="Degrees about +Y. An item's local front is -Z before rotation (2.4).",
            ge=0.0,
            lt=360.0,
        ),
    ]
    source: Literal["detected", "user_kept"]


class Appearance(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    walls: dict[str, common_schema.SurfaceAppearance] | None = None
    floor: common_schema.SurfaceAppearance | None = None
    ceiling: common_schema.SurfaceAppearance | None = None
    tier: Literal[0, 1]


class Source(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: Annotated[str, Field(min_length=1)]
    factor: Annotated[float, Field(gt=0.0)]
    weight: Annotated[float | None, Field(ge=0.0, le=1.0)] = None


class Scale(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    factor: Annotated[float, Field(gt=0.0)]
    sources: list[Source]
    confidence: Literal["high", "medium", "low"]
    user_calibrated: bool


class Quality(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    coverage_pct: Annotated[float, Field(ge=0.0, le=100.0)]
    frames_used: Annotated[int, Field(ge=0)]
    warnings: Annotated[
        list[
            Literal[
                "MIRROR_OR_GLASS_DETECTED",
                "LOW_LIGHT",
                "STRONG_BACKLIGHT",
                "CURVED_WALL_APPROXIMATED",
                "SLOPED_CEILING_UNSUPPORTED",
                "MULTI_LEVEL_FLOOR_UNSUPPORTED",
                "OPEN_BOUNDARY_PRESENT",
                "WALL_BASE_OCCLUDED",
                "DOOR_POSSIBLY_MISSED",
                "DOOR_SWING_UNKNOWN",
                "CEILING_NOT_OBSERVED",
                "SCALE_UNCALIBRATED",
                "LOW_COVERAGE",
            ]
        ],
        Field(
            description="Machine-readable warning codes from the known-limitations list (3.11), shown to the user rather than swallowed."
        ),
    ]


class RoomModel(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Annotated[
        int,
        Field(
            description="Version of the schema set the document was written against.",
            ge=0,
        ),
    ]
    pipeline_version: Annotated[
        str,
        Field(
            pattern="^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-[0-9A-Za-z.-]+)?$"
        ),
    ]
    units: Literal["mm"]
    up: Literal["+Y"]
    floor_polygon: Annotated[
        list[common_schema.Point2Mm],
        Field(
            description="Counter-clockwise [x, z] vertices in mm. Closed implicitly: the last vertex joins the first. Must be simple (non-self-intersecting); area is sanity-checked to 3-150 m2 (3.6).",
            min_length=3,
        ),
    ]
    ceiling_height_mm: Annotated[
        int,
        Field(description="Floor to ceiling. Sanity range from 3.6.", ge=2000, le=4500),
    ]
    ceiling_observed: Annotated[
        bool,
        Field(
            description="False when the ceiling was never properly seen and the height came from wall-top evidence or the 2400mm prior. Confidence in `scale` should reflect that."
        ),
    ]
    walls: list[Wall]
    openings: list[Opening]
    fixed_obstacles: Annotated[
        list[FixedObstacle],
        Field(
            description="Things that are not going anywhere: radiators, fireplaces, built-ins, columns, plus anything the user chose to keep."
        ),
    ]
    appearance: Annotated[
        Appearance | None,
        Field(
            description="Per-surface colour and material for the viewer. Tier 0 is flat colour, tier 1 adds textures (3.7)."
        ),
    ] = None
    scale: Annotated[
        Scale,
        Field(
            description="How the metric scale was arrived at, and how much to trust it. Never present a guess as a fact (3.11)."
        ),
    ]
    quality: Quality
