"""GENERATED by packages/schemas/scripts/generate.mjs. Do not edit."""
from __future__ import annotations
from typing import Annotated, Literal
from pydantic import BaseModel, ConfigDict, Field, RootModel
from . import common_schema


class Measured(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    min_walkway_mm: Annotated[int | None, Field(ge=0)] = None
    free_floor_pct: Annotated[float | None, Field(ge=0.0, le=100.0)] = None
    total_price: common_schema.MoneyCents | None = None


class RelatedId(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class Violation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: Annotated[
        Literal[
            "H1_OUTSIDE_FLOOR",
            "H2_ITEM_OVERLAP",
            "H3_OBSTACLE_OVERLAP",
            "H4_DOOR_KEEPOUT",
            "H5_TOO_TALL",
            "H6_CIRCULATION_BLOCKED",
            "H7_OVER_BUDGET",
            "S1_WALKWAY_TIGHT",
            "S2_CATEGORY_CLEARANCE",
            "S3_WINDOW_BLOCKED",
            "S4_BACK_NOT_TO_WALL",
            "S5_OVERSIZED_FOR_ROOM",
            "S6_PRICE_STALE_OR_UNAVAILABLE",
        ],
        Field(
            description="The rule ids from the 5.5 tables. Closed list so violations can be counted and tested rather than grepped."
        ),
    ]
    severity: Annotated[
        Literal["hard", "soft"],
        Field(
            description="Hard blocks an AI layout and shows red in manual editing. Soft is a warning the user may ignore."
        ),
    ]
    message: Annotated[
        str,
        Field(
            description="The sentence shown to the user, with the measurement in it. For example: walkway narrows to 710 mm between the sofa and the bookshelf.",
            max_length=300,
            min_length=1,
        ),
    ]
    measured_mm: Annotated[
        int | None,
        Field(
            description="The value that triggered the rule, where the rule is about a distance."
        ),
    ] = None
    limit_mm: Annotated[
        int | None,
        Field(
            description="The threshold it failed against, so the UI can say by how much."
        ),
    ] = None
    related_ids: Annotated[
        list[RelatedId] | None,
        Field(
            description="Other items, walls, openings or obstacles involved. An overlap is never about one item alone."
        ),
    ] = None


class Item(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    item_id: Annotated[str, Field(max_length=64, min_length=1)]
    violations: list[Violation]


class ValidationReport(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Annotated[
        int,
        Field(
            description="Version of the schema set the document was written against.",
            ge=0,
        ),
    ]
    fits: Annotated[
        bool,
        Field(
            description="The headline. True when there is no hard violation. Soft violations are warnings and do not clear this flag."
        ),
    ]
    violations: Annotated[
        list[Violation],
        Field(
            description="Global violations, i.e. ones that are not about a single item: circulation (H6), total price (H7), main walkway (S1)."
        ),
    ]
    items: Annotated[
        list[Item], Field(description="Per-item findings, keyed by layout item id.")
    ]
    measured: Annotated[
        Measured | None,
        Field(
            description="Numbers the UI can show even when nothing is wrong: narrowest walkway, total price, free floor fraction."
        ),
    ] = None
